/**
 * PediScreen AI — centralized disclaimer constants for UI, API, and PDF.
 * Use these verbatim for legal consistency across consent modals, banners, and exports.
 * For production and regulatory filings, consult legal counsel.
 */

/** Short banner (1 line) — clinician & CHW dashboards */
export const DISCLAIMER_SHORT =
  "PediScreen AI: an AI-assisted screening aid for clinicians and CHWs. Outputs are draft suggestions — clinician review required.";

/** Draft disclaimer — shown above every draft report */
export const DISCLAIMER_DRAFT =
  "Draft (AI-Assisted): This summary was generated by PediScreen AI to assist clinical review. It combines parent input, questionnaire scores, and optional images. It is not a diagnosis. A qualified clinician must review, edit if needed, and sign before adding to the medical record.";

/** PDF footer — placed on every exported PDF report */
export const PDF_FOOTER =
  "PediScreen AI — Draft technical report. AI-assisted content; clinician review and sign-off required prior to clinical use.";

/** Parent-facing consent modal header */
export const CONSENT_MODAL_HEADER = "PediScreen AI — Consent to assist your child's screening";

/** Parent-facing one-liner (badges / tiny UI elements) */
export const PARENT_ONE_LINER =
  "We use a privacy-first AI tool to help clinicians summarize screenings. Your child's clinician reviews every report.";

/** Parent-facing short paragraph (consent modal intro) */
export const PARENT_CONSENT_INTRO =
  "PediScreen helps your child's healthcare team by creating a clear, easy-to-read screening summary. The tool uses secure, private methods and does not provide a diagnosis. A clinician will review the draft and share any recommended next steps with you.";

/** Parent-facing medium paragraph (FAQ / more detail) */
export const PARENT_FAQ_PARAGRAPH =
  "We use an AI tool to help organize the information you provide and suggest items for clinicians to review. This helps clinicians spend more time talking with families and less time on paperwork. We redact personal identifiers before any external processing, and clinicians must review and sign the final report before it's used in care. You can opt out of sharing images or of using non-identifiable data for model improvement.";

/** FDA SaMD-aligned radiology triage disclaimer (SaMD Category II) */
export const FDA_RADIOLOGY_DISCLAIMER =
  "This output is generated by a clinical decision support system. It does not provide a diagnosis and must be reviewed by a qualified clinician.";

/** Model confidence tooltip */
export const MODEL_CONFIDENCE_TOOLTIP =
  "Model confidence: %pct% — this is an AI estimate of how strongly the data supports the flagged concern. Clinicians use this along with their assessment.";

/** Parent FAQ entries */
export const PARENT_FAQ = [
  {
    q: "Will the AI diagnose my child?",
    a: "No. The AI produces a draft summary to help clinicians. Only a clinician can diagnose or recommend treatment.",
  },
  {
    q: "Is my child's photo safe?",
    a: "Yes — photos are optional, stored securely, and personally identifying details are removed before any model processing unless you explicitly consent otherwise.",
  },
  {
    q: "Can I opt out of data sharing for research?",
    a: "Yes — consent options let you choose whether de-identified data may be used to improve the system.",
  },
] as const;
