"""
PediScreen AI — centralized disclaimer constants for UI, API, and PDF.
Use these verbatim for legal consistency across consent modals, banners, and exports.
For production and regulatory filings, consult legal counsel.
"""

# Short banner (1 line) — clinician & CHW dashboards
DISCLAIMER_SHORT = (
    "PediScreen AI: an AI-assisted screening aid for clinicians and CHWs. "
    "Outputs are draft suggestions — clinician review required."
)

# Draft disclaimer — shown above every draft report
DISCLAIMER_DRAFT = (
    "Draft (AI-Assisted): This summary was generated by PediScreen AI to assist clinical review. "
    "It combines parent input, questionnaire scores, and optional images. It is not a diagnosis. "
    "A qualified clinician must review, edit if needed, and sign before adding to the medical record."
)

# PDF footer — placed on every exported PDF report
PDF_FOOTER = (
    "PediScreen AI — Draft technical report. AI-assisted content; "
    "clinician review and sign-off required prior to clinical use."
)

# API response header value
API_DISCLAIMER_HEADER = (
    "This content is AI-assisted clinical decision support. "
    "It is not a diagnosis. Clinician review required."
)

# FDA SaMD-aligned radiology triage disclaimer (SaMD Category II)
# "Drives clinical management but does not diagnose or treat"
FDA_RADIOLOGY_DISCLAIMER = (
    "This output is generated by a clinical decision support system. "
    "It does not provide a diagnosis and must be reviewed by a qualified clinician."
)

# Intended Use Statement (for regulatory documentation)
FDA_INTENDED_USE_RADIOLOGY = (
    "PediScreen AI Radiology Triage is a clinical decision support software intended to "
    "assist qualified healthcare professionals by prioritizing radiology studies for review "
    "based on AI-derived patterns. The software does not provide diagnostic conclusions "
    "and is not intended to replace clinical judgment."
)

# Parent-facing consent modal header
CONSENT_MODAL_HEADER = "PediScreen AI — Consent to assist your child's screening"

# Parent-facing consent modal paragraph
CONSENT_MODAL_PARAGRAPH = (
    "We use secure, privacy-first tools to create a supportive screening summary for clinicians. "
    "The tool helps prepare a draft report — your child's healthcare team will review and decide any next steps. "
    "You can choose whether images or de-identified data may be retained for improvement."
)
